name: syncpact_mobile
description: "An Application to Facilitate Wireless Android Folder Sync."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  flutter_animation_progress_bar: ^2.3.1
  nearby_connections: ^3.3.0
  image_picker: ^0.8.9
  file_picker: ^8.0.0+1
  permission_handler: ^11.3.1
  file_manager: ^1.0.2
  controller: ^0.1.12
  english_words: ^4.0.0
  provider: ^6.1.2
  path_provider: ^2.1.3
  file_icon: ^1.0.0
  mime: ^1.0.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/landing_img.png

  